### ISSUE TITLE
Crash when placing down a Framed Slant

### ISSUE THREAD

**Issue by angelnc1989** [EpicSquid/Blockcraftery#1]
Minecraft 1.12.2
Forge 14.23.4.2732
Blockcraftery 0.1.3

Crash report: [https://pastebin.com/fTrK78am]( https://pastebin.com/fTrK78am)
Description:
The screen turns black as soon as I place the block and then crashes a few seconds after that. The world can't be entered again without crashing.

**Comment by EpicSquid** [comment]
There appears to be an issue with codechicken lib causing this. Please ask them.

**Comment by covers1624** [comment]
Np, didn't mean to sound hostile either. Glad i could point you in the right direction :D

**Comment by EpicSquid** [comment]
Still getting used to the rendering magic in blockcraftery, so thanks for the help!

**Comment by covers1624** [comment]
Np, poke me any time.

**Comment by psychofad** [comment]
Not trying to be "that guy" or anything, but is this still being worked on/fixed as I am getting this error now at my base on a server.  I was at my base, took an airship from there to explore for some apatite I needed and used a /home command and my screen went all white and the client crashed.  Now every time I try to login I am getting the same crash.  I had recently remove my chunkloader from keeping that area loaded, so I am fairly certain something got borked on reloading that chunk when I teleported in, and the game was nice enough to save that for me to see every time I enter the chunk (login) and kick me back to desktop!  Is there a way I can somehow turn off the rendering of those blocks to prevent the tesselation clientside long enough for me to log in and break the offending blocks or is that even possible?

**Comment by Brycey92** [comment]
Does this issue still exist? I'm considering adding the mod to my pack, but I can't if it has such a breaking bug.

**Comment by EpicSquid** [comment]
It should be fixed. If it isn't, just let me know and I will try to fix it yet again

**Comment by Brycey92** [comment]
Thanks for the quick response! I'll give it a shot in my test environment.

@angelnc1989 or @psychofad have you tested newer versions of the mods on your worlds that were causing the crash?

**Comment by Birgliss** [comment]
[crash](https://gist.github.com/Birgliss/8667957788945f241765601953a99222) seems to still persist on version 1.1.0 with forge version 2772.
