### ISSUE TITLE
All Blockcraftery blocks invisible

### ISSUE THREAD

**Issue by angelnc1989** [EpicSquid/Blockcraftery#2]
Minecraft 1.12.2
Forge 14.23.4.2749
Blockcraftery 0.1.3
elulib 0.1.12

When placing down a block from Blockcraftery a message appears in chat saying "CCL Caught an exception rendering a block. See the log for info."
The block is then invisible.
![image](https://user-images.githubusercontent.com/5382585/44004026-305c6cea-9e5c-11e8-8c32-13af56fb987c.png)
Using a block on it makes the same message appear and changes nothing.

[Log](https://paste.ubuntu.com/p/jBtgZXjr8S/)

**Comment by angelnc1989** [comment]
It still happens

**Comment by EpicSquid** [comment]
Pretty sure this is fixed now. closing since it is extremely old and I haven't seen the issue in newer versions.

**Comment by bool3max** [comment]
Still occurs for me on the latest 1.12.2 build, same log message in the chat.
